---
schema:
  procedures: {}
  tables:
    users:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
      fields:
        created_at:
          data_type: datetime
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: created_at
          order: 5
          size:
            - 0
        email:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: email
          order: 2
          size:
            - 128
        id:
          data_type: char
          default_value: ~
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 64
        password_hash:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: password_hash
          order: 3
          size:
            - 64
        role:
          data_type: char
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: role
          order: 4
          size:
            - 1
        updated_at:
          data_type: datetime
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: updated_at
          order: 6
          size:
            - 0
      indices: []
      name: users
      options: []
      order: 1
  triggers: {}
  views: {}
translator:
  add_drop_table: 0
  filename: ~
  no_comments: 0
  parser_args:
    sources:
      - User
  parser_type: SQL::Translator::Parser::DBIx::Class
  producer_args: {}
  producer_type: SQL::Translator::Producer::YAML
  show_warnings: 0
  trace: 0
  version: 0.11021
